baseURL = '/'
languageCode = 'en-us'
title = 'Zaid'
theme = 'risotto'

sectionPagesMenu = "main"

[params.about]
  title = "Zaid"
  description = "Software engineer. I like movies too!"
  logo_image = "/zaid.jpeg"
  email = "azaidrahman@gmail.com"

[[params.socialLinks]]
  icon = "fa-brands fa-github"
  title = "GitHub"
  url = "https://github.com/azaidrahman/"

[[params.socialLinks]]
  icon = "fa-brands fa-linkedin"
  title = "LinkedIn"
  url = "https://www.linkedin.com/in/abdullah-zaid/"

[[params.socialLinks]]
  icon = "fa-brands fa-square-letterboxd"
  title = "Letterboxd"
  url = "https://letterboxd.com/sanisideup/"

[markup.goldmark.renderer]
  unsafe = true
